version: '3.1'

services:
  postgres:
    image: 'postgres:14.4-alpine'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=rabo
      - POSTGRES_PASSWORD=rabo1234
      - POSTGRES_DB=rabo
    ports:
      - '5434:5432'